// Built-in English study vocabulary (~7,500 words) for Japanese learners.
// The dataset is generated by scripts/build-vocab.mjs from openly licensed
// sources (CEFR-J, EJDict, FrequencyWords) — see assets/vocab.NOTICE.md.
//
// Entries are pre-sorted by frequency (most common first), so each deck reads
// in a pedagogically sensible order out of the box.

import raw from '../assets/vocab.json';

export type CEFR = 'A1' | 'A2' | 'B1' | 'B2' | 'C1' | 'C2';

export interface VocabWord {
  w: string; // English headword
  j: string; // Japanese gloss
  p: string; // part of speech (名/動/形…)
  l: CEFR; // CEFR level
  r: number; // frequency rank (lower = more common)
  b?: 1; // TOEIC / business tag
}

export const VOCAB = raw as VocabWord[];

const byWord = new Map(VOCAB.map((e) => [e.w, e]));
export const lookupWord = (w: string): VocabWord | undefined => byWord.get(w);

export interface DeckDef {
  id: string;
  title: string;
  subtitle: string;
  match: (e: VocabWord) => boolean;
}

export const DECKS: DeckDef[] = [
  { id: 'jhs', title: '中学レベル', subtitle: '基礎の基礎（A1・A2）', match: (e) => e.l === 'A1' || e.l === 'A2' },
  { id: 'hs1', title: '高校 基礎', subtitle: 'センター/共通テスト基礎（B1）', match: (e) => e.l === 'B1' },
  { id: 'hs2', title: '高校 発展', subtitle: '難関・大学基礎（B2）', match: (e) => e.l === 'B2' },
  { id: 'toeic', title: 'TOEIC・ビジネス', subtitle: '仕事で頻出のビジネス語', match: (e) => !!e.b },
  { id: 'adv', title: '上級', subtitle: 'ネイティブ級（C1・C2）', match: (e) => e.l === 'C1' || e.l === 'C2' },
];

const deckCache = new Map<string, VocabWord[]>();
export function deckWords(deckId: string): VocabWord[] {
  const cached = deckCache.get(deckId);
  if (cached) return cached;
  const def = DECKS.find((d) => d.id === deckId);
  const list = def ? VOCAB.filter(def.match) : [];
  deckCache.set(deckId, list);
  return list;
}
